/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp.reservation;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SHADOWRATH
 */
public class ReservationHallDetails extends javax.swing.JFrame {
    
    private Connection connection = DBConnection.getDbConnection();
     public String custID;
     public static String Hallname ;
     ResultSet rs;
     public int row_n = -1;
     public String n;

    /**
     * Creates new form ReservationRoomDetails
     */
    public ReservationHallDetails() {
        initComponents();        
        System.out.println("Hall Name :"+Hallname);
    }
    
    
     public void updateData(String v, String hall_name){
        System.out.println("GetData Executed");
        n = hall_name;
        try{
            String sql = "SELECT customer.Cname,customer.CEmail,customer.NIC,customer.CContact,Reservation.checkIn from customer,Reservation where customer.Cid = Reservation.CusID AND Hname ='"+v+"'";
            System.out.println("SQL CODE : "+sql);
            
            PreparedStatement pst;
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery(); 
            System.out.println("Rs received");
            
            while (rs.next()) {
                System.out.println("exe");
                ////////////////////////
                //System.out.println("Rs Output [0]: "+rs.getString(1));
                //System.out.println("Rs Output [1]: "+rs.getString(1));
                HIName.setText(rs.getString(1));
                HIEmail.setText(rs.getString(2));
                HINIC.setText(rs.getString(3));
                HIContact.setText(rs.getString(4));
                HICIn.setText(rs.getString(5));
                
                
                
                
                /////////////////////////
                
            }                  

        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }
     

    
    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTNReservation = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BTNadd = new javax.swing.JButton();
        BTNdelete = new javax.swing.JButton();
        BTNupdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HIName = new javax.swing.JLabel();
        HIEmail = new javax.swing.JLabel();
        HIContact = new javax.swing.JLabel();
        HICIn = new javax.swing.JLabel();
        JLB6 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HINIC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        BTNReservation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNReservation.setText("Reservation");
        BTNReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReservationActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("LOGOUT");

        BTNadd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNadd.setText("ADD");
        BTNadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNaddActionPerformed(evt);
            }
        });

        BTNdelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNdelete.setText("DELETE");
        BTNdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdeleteActionPerformed(evt);
            }
        });

        BTNupdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNupdate.setText("UPDATE");
        BTNupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNupdateActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name :");

        jLabel3.setText("Email :");

        jLabel4.setText("Contact No :");

        jLabel5.setText("Check In :");

        HIName.setText("not booked");

        HIEmail.setText("not booked");

        HIContact.setText("not booked");

        HICIn.setText("not booked");

        JLB6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLB6.setText("jLabel6");

        jLabel6.setText("NIC  :");

        HINIC.setText("not booked");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JLB6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BTNReservation)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(BTNadd)
                            .addGap(86, 86, 86)
                            .addComponent(BTNdelete)
                            .addGap(61, 61, 61)
                            .addComponent(BTNupdate)
                            .addGap(72, 72, 72)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HICIn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HIContact, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HIEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HIName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HINIC))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLB6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTNReservation)
                        .addComponent(jButton2)
                        .addComponent(jButton1)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(HIName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(HIEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(HINIC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HIContact)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(HICIn))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNdelete)
                    .addComponent(BTNadd)
                    .addComponent(BTNupdate))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReservationActionPerformed
        close();
        ReservationHome c = new ReservationHome();
        c.setVisible(true);
    }//GEN-LAST:event_BTNReservationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
        HallReservation i = new HallReservation();
        i.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTNaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNaddActionPerformed
        close();
        String p = HIName.getText().toString();
        if(p == "not booked"){
            ReservationHInput1 x = new ReservationHInput1();
            x.JLBName.setText(JLB6.getText());
            x.setVisible(true);
            RoomReservation k = new RoomReservation();
            DefaultTableModel model = (DefaultTableModel) k.jTable2.getModel();
            int row = k.jTable2.getSelectedRow()+1;
            x.jLabel1.setText("Enter Reservation Details for Hall ");
        }else{
            System.out.println("false");
            JOptionPane.showMessageDialog(null, "This Hall is already booked");
        
        }
    }//GEN-LAST:event_BTNaddActionPerformed

    private void BTNdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdeleteActionPerformed
 try{
            
            String sql = "DELETE from Reservation where Hname = ?";
            
            String sqlx = "UPDATE Halls SET status_= FALSE WHERE HallName = ?";
            
            PreparedStatement pst;
            PreparedStatement pstx;
            pst = connection.prepareStatement(sql);
            pstx = connection.prepareStatement(sqlx);
            pst.setString(1, JLB6.getText());
            pstx.setString(1, JLB6.getText());
            int m = JOptionPane.showConfirmDialog(null,"Delete this reservation","DELETE",JOptionPane.YES_NO_OPTION);
            if(m == 0){
            pst.executeUpdate();
            pstx.executeUpdate();
            close();
            HallReservation z = new HallReservation();
            z.setVisible(true);
            }
            else{}
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_BTNdeleteActionPerformed

    private void BTNupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNupdateActionPerformed
       try{
           System.out.println("test 1");
           
            System.out.println("test3");
            String sql = "SELECT customer.Cid,customer.Cname,customer.CEmail,customer.NIC,customer.CContact,Reservation.checkIn from customer,Reservation where customer.Cid = Reservation.CusID AND Hname ='"+n+"'";
            System.out.println("SQL CODE : "+sql);
            System.out.println("test4");
            
            PreparedStatement pst;
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery(); 
            System.out.println("Rs received");
            
            close();
            ReservationUpdateInput k = new ReservationUpdateInput();
            k.JLBName.setText(JLB6.getText());
            
            while (rs.next()) {
                System.out.println("exe");
                
                
                k.CID.setText(rs.getString(1));
                k.HinputName.setText(rs.getString(2));
                k.HinputEmail.setText(rs.getString(3));
                k.HNIC.setText(rs.getString(4));
                k.HinputContact.setText(rs.getString(5));
                //k.HCheckIN.setDateFormatString(rs.getString(6));
                //k.HCheckIN.setText(rs.getString(6).toString());
                
                String sDate1=rs.getString(6);  
                //Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(sDate1);
                Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(sDate1);
                k.HCheckIN.setDate(date1);
            }
            System.out.println("dab");
            k.jLabel1.setText("Update Reservation for Hall");
            k.setVisible(true);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         
        
    }//GEN-LAST:event_BTNupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationHallDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationHallDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationHallDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationHallDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationHallDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNReservation;
    private javax.swing.JButton BTNadd;
    private javax.swing.JButton BTNdelete;
    private javax.swing.JButton BTNupdate;
    private javax.swing.JLabel HICIn;
    private javax.swing.JLabel HIContact;
    private javax.swing.JLabel HIEmail;
    private javax.swing.JLabel HINIC;
    private javax.swing.JLabel HIName;
    public javax.swing.JLabel JLB6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
