/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp.reservation;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SHADOWRATH
 */
public class ReservationRoomDetails extends javax.swing.JFrame {
    
     private Connection connection = DBConnection.getDbConnection();
     public String custID;
     public static int roomNo ;
     ResultSet rs;
     public int f;

    /**
     * Creates new form ReservationRoomDetails
     */
    public ReservationRoomDetails() {
        initComponents();
        //getData();
        System.out.println("Room No :"+roomNo);
    }
    
    public void updateData(int no){
        System.out.println("GetData Executed");
        f = no;
        try{
            String sql = "SELECT customer.Cname,customer.CEmail,customer.NIC,customer.CContact,Reservation.checkIn,Reservation.checkOut from customer,Reservation where customer.Cid = Reservation.CusID AND Rno ='"+no+"'";
            System.out.println("SQL CODE : "+sql);
            //String sql = "SELECT Room_Number,status_ from Reservations WHWRE rooms="+roomNo+"";
            PreparedStatement pst;
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery(); 
            System.out.println("Rs received");
            
            while (rs.next()) {
                System.out.println("exe");
                ////////////////////////
                //System.out.println("Rs Output [0]: "+rs.getString(1));
                //System.out.println("Rs Output [1]: "+rs.getString(1));
                lblName.setText(rs.getString(1));
                lblEmail.setText(rs.getString(2));
                lblNIC.setText(rs.getString(3));
                lblContact.setText(rs.getString(4));
                lblCIn.setText(rs.getString(5));
                lblCOut.setText(rs.getString(6));
                
                
                
                /////////////////////////
                
            }                  

        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }

          public void initialize(int roomNo){
                /* try {  
          String sql = "SELECT Room_Number,status_ from Reservations WHWRE rooms="+roomNo+"";
          PreparedStatement pst;
              pst = connection.prepareStatement(sql);
          ResultSet rs = pst.executeQuery();
                     System.out.println(jTable1);
                     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                   model.setRowCount(0);
                 
                      List<itp.reservation.model.RoomReservation> arrList = new ArrayList<itp.reservation.model.RoomReservation>(); 
                      
                while (rs.next()) {
                     itp.reservation.model.RoomReservation roomReservation = new   itp.reservation.model.RoomReservation();
                     
                     roomReservation.setRoomNumber(rs.getInt(1));
                     roomReservation.setStatus(rs.getBoolean(2));
                     System.out.println(roomReservation);
                     
                       arrList.add(roomReservation);
                  

                }
               for(int i = arrList.size()-1 ; i >=0 ; i--){
                   itp.reservation.model.RoomReservation tempRoom = arrList.get(i);
                   if(tempRoom.isStatus()){
                  model.insertRow(0,new Object[]{tempRoom.getRoomNumber(),STATUS_BOOKED});
               }
                   else{
                     model.insertRow(0,new Object[]{tempRoom.getRoomNumber(),STATUS_NOT_BOOKED});   
                   }
               }
               
      
            jTable2.setModel(model);
                   
                   
          
     
        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
                */
      }
    
    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNadd = new javax.swing.JButton();
        BTNdelete = new javax.swing.JButton();
        BTNupdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        VEmail = new javax.swing.JLabel();
        VContact = new javax.swing.JLabel();
        VCin = new javax.swing.JLabel();
        VCout = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblCOut = new javax.swing.JLabel();
        VNIC = new javax.swing.JLabel();
        lblCIn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlb1 = new javax.swing.JLabel();
        jlb2 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        BTNReservation = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BTNadd.setBackground(new java.awt.Color(153, 204, 0));
        BTNadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNadd.setText("ADD");
        BTNadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNaddActionPerformed(evt);
            }
        });

        BTNdelete.setBackground(new java.awt.Color(153, 204, 0));
        BTNdelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNdelete.setText("DELETE");
        BTNdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdeleteActionPerformed(evt);
            }
        });

        BTNupdate.setBackground(new java.awt.Color(153, 204, 0));
        BTNupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNupdate.setText("UPDATE");
        BTNupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNupdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name    : ");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblName.setText("not booked");

        VEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VEmail.setText("Email     :");

        VContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VContact.setText("Contact :");

        VCin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VCin.setText("CheckIn :");

        VCout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VCout.setText("CheckOut :");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("not booked");

        lblNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNIC.setText("not booked");

        lblContact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContact.setText("not booked");

        lblCOut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCOut.setText("not booked");

        VNIC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VNIC.setText("NIC      :");

        lblCIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCIn.setText("not booked");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlb1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlb1.setText("jLabel1");

        jlb2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlb2.setText("jLabel1");

        Backbtn.setBackground(new java.awt.Color(153, 204, 0));
        Backbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        BTNReservation.setBackground(new java.awt.Color(153, 204, 0));
        BTNReservation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNReservation.setText("Reservation");
        BTNReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReservationActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("LogOut");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BTNReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNadd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(BTNdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241)
                .addComponent(BTNupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VEmail)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VContact, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblNIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VCout)
                                .addGap(58, 58, 58)
                                .addComponent(lblCOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(571, 571, 571))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VCin)
                        .addGap(68, 68, 68)
                        .addComponent(lblCIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VContact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContact, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VCin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VCout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCOut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNadd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReservationActionPerformed
        close();
        ReservationHome z = new ReservationHome();
        z.setVisible(true);
    }//GEN-LAST:event_BTNReservationActionPerformed

    private void BTNaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNaddActionPerformed
        close();
        String p = lblName.getText().toString();
        if(p == "not booked"){
            ReservationRInput x = new ReservationRInput();
            x.jlbNum.setText(jlb2.getText());
            x.setVisible(true);
            RoomReservation k = new RoomReservation();
            DefaultTableModel model = (DefaultTableModel) k.jTable2.getModel();
            int row = k.jTable2.getSelectedRow()+1;
            x.jLabel1.setText("Enter Reservation Details for Room ");
        }else{
            System.out.println("false");
            JOptionPane.showMessageDialog(null, "This room is already booked");
        
        }
        
    }//GEN-LAST:event_BTNaddActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        close();
       
            RoomReservation k = new RoomReservation();
            k.setVisible(true);
        
    }//GEN-LAST:event_BackbtnActionPerformed

    private void BTNdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdeleteActionPerformed
        try{
            
            String sql = "DELETE from Reservation where Rno = ?";
            
            String sqlx = "UPDATE Rooms SET status_= FALSE WHERE Room_Number = ?";
            
            PreparedStatement pst;
            PreparedStatement pstx;
            pst = connection.prepareStatement(sql);
            pstx = connection.prepareStatement(sqlx);
            pst.setString(1, jlb2.getText());
            pstx.setString(1, jlb2.getText());
            int m = JOptionPane.showConfirmDialog(null,"Delete this reservation","DELETE",JOptionPane.YES_NO_OPTION);
            if(m == 0){
            pst.executeUpdate();
            pstx.executeUpdate();
            close();
            RoomReservation z = new RoomReservation();
            z.setVisible(true);
            }
            else{}
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BTNdeleteActionPerformed

    private void BTNupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNupdateActionPerformed
   try{
           
            String sql = "SELECT customer.Cid,customer.Cname,customer.CEmail,customer.NIC,customer.CContact,Reservation.checkIn,Reservation.checkOut from customer,Reservation where customer.Cid = Reservation.CusID AND Rno ='"+f+"'";
            System.out.println("SQL CODE : "+sql);
            System.out.println("test4");
            
            PreparedStatement pst;
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery(); 
            System.out.println("Rs received");
            
            close();
            ReservationRoomUpdateInput k = new ReservationRoomUpdateInput();
            k.JLBName.setText(jlb2.getText());
            
            while (rs.next()) {
                System.out.println("exe");
                
                
                k.CID.setText(rs.getString(1));
                k.RinputName.setText(rs.getString(2));
                k.RinputEmail.setText(rs.getString(3));
                k.RNIC.setText(rs.getString(4));
                k.RinputContact.setText(rs.getString(5));
                
                String sDate1=rs.getString(6); 
                String sDate2=rs.getString(7);
               
                java.util.Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(sDate1);
                java.util.Date date2=new SimpleDateFormat("yyyy-MM-dd").parse(sDate2);
                
                k.RCheckIN.setDate(date1);
                k.RCheckOut.setDate(date2);
                
                
            }
            System.out.println("dab");
            k.jLabel1.setText("Update Reservation for Room");
            k.setVisible(true);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         
                
    }//GEN-LAST:event_BTNupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationRoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationRoomDetails.class.getNlblNIC(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationRoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationRoomDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationRoomDetails().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNReservation;
    private javax.swing.JButton BTNadd;
    private javax.swing.JButton BTNdelete;
    private javax.swing.JButton BTNupdate;
    private javax.swing.JButton Backbtn;
    private javax.swing.JLabel VCin;
    private javax.swing.JLabel VContact;
    private javax.swing.JLabel VCout;
    private javax.swing.JLabel VEmail;
    private javax.swing.JLabel VNIC;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jlb1;
    public javax.swing.JLabel jlb2;
    private javax.swing.JLabel lblCIn;
    private javax.swing.JLabel lblCOut;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables

}
