/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp.reservation;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author SHADOWRATH
 */
public class RoomReservation extends javax.swing.JFrame {

    /**
     * Creates new form RoomReservation
     */
    
    private Connection connection = DBConnection.getDbConnection();
    private static final String STATUS_BOOKED = "Booked";
    private static final String STATUS_NOT_BOOKED ="Not booked";
    
    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    } 
    
    public RoomReservation() {
   
        initComponents();
             initialize();
    }
    
     
    
      public void initialize(){
                 try {  
          String sql = "SELECT Room_Number,status_ from Rooms";
          PreparedStatement pst;
              pst = connection.prepareStatement(sql);
          ResultSet rs = pst.executeQuery();
                     System.out.println(jTable2);
                     DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                   model.setRowCount(0);
                 
                      List<     itp.reservation.model.RoomReservation> arrList = new ArrayList<     itp.reservation.model.RoomReservation>(); 
                      
                while (rs.next()) {
                          itp.reservation.model.RoomReservation roomReservation = new   itp.reservation.model.RoomReservation();
                     
                     roomReservation .setRoomNumber(rs.getInt(1));
                     roomReservation.setStatus(rs.getBoolean(2));
                     System.out.println(roomReservation);
                     
                       arrList.add(roomReservation);
                     
                    
                     

                }
               for(int i = arrList.size()-1 ; i >=0 ; i--){
                   itp.reservation.model.RoomReservation tempRoom = arrList.get(i);
                   if(tempRoom.isStatus()){
                  model.insertRow(0,new Object[]{tempRoom.getRoomNumber(),STATUS_BOOKED});
               }
                   else{
                     model.insertRow(0,new Object[]{tempRoom.getRoomNumber(),STATUS_NOT_BOOKED});   
                   }
               }
               
      
            jTable2.setModel(model);
                   
                   
          
     
        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
                
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTNHome = new javax.swing.JButton();
        BTNlogout = new javax.swing.JButton();
        ReservationRhistory = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ViewDetailsbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Reservation Rooms");

        BTNHome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNHome.setText("Reservation");
        BTNHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHomeActionPerformed(evt);
            }
        });

        BTNlogout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNlogout.setText("LOGOUT");

        ReservationRhistory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ReservationRhistory.setText("Reservation History");
        ReservationRhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationRhistoryActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ViewDetailsbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewDetailsbtn.setText("View Details");
        ViewDetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsbtnActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Room Number", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(BTNHome)
                        .addGap(18, 18, 18)
                        .addComponent(BTNlogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ReservationRhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(ViewDetailsbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTNHome)
                        .addComponent(BTNlogout))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReservationRhistory)
                    .addComponent(ViewDetailsbtn))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
        ReservationHome z = new ReservationHome();
        z.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ReservationRhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationRhistoryActionPerformed
        close();
        ResRHistory l = new ResRHistory();
        l.setVisible(true);
    }//GEN-LAST:event_ReservationRhistoryActionPerformed

    private void BTNHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHomeActionPerformed
        close();
        ReservationHome c = new ReservationHome();
        c.setVisible(true);
    }//GEN-LAST:event_BTNHomeActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel tblModel = (DefaultTableModel)jTable2.getModel();
       
        //Set data to the text feilds when a row is selected
       
        String roomNo = tblModel.getValueAt(jTable2.getSelectedRow(), 0).toString();
        String status = tblModel.getValueAt(jTable2.getSelectedRow(), 1).toString();
        
        
     
        System.out.println(roomNo);
        System.out.println(status);
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void ViewDetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsbtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        if(jTable2.getSelectedRow()!=-1){
                close();
                ReservationRoomDetails l = new ReservationRoomDetails();
                int row = jTable2.getSelectedRow()+1;
                l.jLabel1.setText("Reservation Details for Room "+row);
                                 try {  
          String sql = "SELECT Cname,CEmail,CContact from customer values ('?,?,?')";
          PreparedStatement pst;
              pst = connection.prepareStatement(sql);
          ResultSet rs = pst.executeQuery();
                  
                     
                   model.setRowCount(0);
                 
                      List<     itp.reservation.model.RoomReservation> arrList = new ArrayList<     itp.reservation.model.RoomReservation>(); 
                      
                while (rs.next()) {
                          itp.reservation.model.RoomReservation roomReservation = new   itp.reservation.model.RoomReservation();
                     
                     roomReservation .setRoomNumber(rs.getInt(1));
                     roomReservation.setStatus(rs.getBoolean(2));
                     System.out.println(roomReservation);
                     
                       arrList.add(roomReservation);
                     
                    
                     

                }
               
               
      
            jTable2.setModel(model);
                   
                   
          
     
        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
                l.setVisible(true);
            
        }
    }//GEN-LAST:event_ViewDetailsbtnActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNHome;
    private javax.swing.JButton BTNlogout;
    private javax.swing.JButton ReservationRhistory;
    private javax.swing.JButton ViewDetailsbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    
}
