/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp.reservation;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author SHADOWRATH
 */
public class RoomReservation extends javax.swing.JFrame {

    /**
     * Creates new form RoomReservation
     */
    
    private Connection connection = DBConnection.getDbConnection();
    private static final String STATUS_BOOKED = "Booked";
    private static final String STATUS_NOT_BOOKED ="Not booked";
    
    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    } 
    
    public RoomReservation() {
   
        initComponents();
             initialize();
    }
    
     
    
      public void initialize(){
                 try {  
          String sql = "SELECT Room_Number,status_ from Rooms";
          PreparedStatement pst;
              pst = connection.prepareStatement(sql);
          ResultSet rs = pst.executeQuery();
                     System.out.println(jTable2);
                     DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                   model.setRowCount(0);
                 
                      List<     itp.reservation.model.RoomReservation> arrList = new ArrayList<     itp.reservation.model.RoomReservation>(); 
                      
                while (rs.next()) {
                          itp.reservation.model.RoomReservation roomReservation = new   itp.reservation.model.RoomReservation();
                     
                     roomReservation .setRoomNumber(rs.getInt(1));
                     roomReservation.setStatus(rs.getBoolean(2));
                     System.out.println(roomReservation);
                     
                       arrList.add(roomReservation);
                     
                    
                     

                }
               for(int i = arrList.size()-1 ; i >=0 ; i--){
                   itp.reservation.model.RoomReservation tempRoom = arrList.get(i);
                   if(tempRoom.isStatus()){
                  model.insertRow(0,new Object[]{tempRoom.getRoomNumber(),STATUS_BOOKED});
               }
                   else{
                     model.insertRow(0,new Object[]{tempRoom.getRoomNumber(),STATUS_NOT_BOOKED});   
                   }
               }
               
      
            jTable2.setModel(model);
                   
                   
          
     
        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
                
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReservationRhistory = new javax.swing.JButton();
        ViewDetailsbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BTNHome = new javax.swing.JButton();
        BTNlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ReservationRhistory.setBackground(new java.awt.Color(153, 204, 0));
        ReservationRhistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ReservationRhistory.setText("Reservation History");
        ReservationRhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationRhistoryActionPerformed(evt);
            }
        });

        ViewDetailsbtn.setBackground(new java.awt.Color(153, 204, 0));
        ViewDetailsbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewDetailsbtn.setText("View Details");
        ViewDetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsbtnActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Room Number", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(153, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Reservation Rooms");

        BTNHome.setBackground(new java.awt.Color(153, 204, 0));
        BTNHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNHome.setText("Reservation");
        BTNHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHomeActionPerformed(evt);
            }
        });

        BTNlogout.setBackground(new java.awt.Color(153, 204, 0));
        BTNlogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNlogout.setText("LogOut");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(BTNHome, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(BTNlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNHome, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReservationRhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewDetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReservationRhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewDetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
        ReservationHome z = new ReservationHome();
        z.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ReservationRhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationRhistoryActionPerformed
        close();
        ResRHistory l = new ResRHistory();
        l.setVisible(true);
    }//GEN-LAST:event_ReservationRhistoryActionPerformed

    
    
    
    private void BTNHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHomeActionPerformed
        close();
        ReservationHome c = new ReservationHome();
        c.setVisible(true);
    }//GEN-LAST:event_BTNHomeActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel tblModel = (DefaultTableModel)jTable2.getModel();
       
        //Set data to the text feilds when a row is selected
       
        String roomNo = tblModel.getValueAt(jTable2.getSelectedRow(), 0).toString();
        String status = tblModel.getValueAt(jTable2.getSelectedRow(), 1).toString();
        
        
     
        System.out.println(roomNo);
        System.out.println(status);
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void ViewDetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsbtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        if(jTable2.getSelectedRow()!=-1){
                close();
                ReservationRoomDetails l = new ReservationRoomDetails();
                int row = jTable2.getSelectedRow()+1;
                l.jlb1.setText("Reservation Details for Room");
                l.jlb2.setText(""+row);
                l.updateData(row);

            /*try {  
            int r = jTable2.getSelectedRow();                           
         
          String sql = "SELECT customer.Cname,customer.CEmail,customer.CContact,Reservation.checkIn,Reservation.checkOut from customer,Reservation where customer.Cid = Reservation.CusID AND Rno = ?";


                 PreparedStatement pst;
              pst = connection.prepareStatement(sql);
              pst.setInt(1,jTable2.getSelectedRow());
          ResultSet rs = pst.executeQuery();
                                    /* System.out.println("print in rs");
                                     System.out.println(rs);
                                     System.out.println("print in rs.next");
                                     System.out.println(rs.next());
                                     //System.out.println("print in rs.first");
                                     System.out.println(rs.first());*/
          
                  
                     
                 /*  model.setRowCount(0);
                 
                      List<     itp.reservation.model.CustomerDetails> arrList = new ArrayList<     itp.reservation.model.CustomerDetails>(); 
                      
                                     System.out.println("before rs.next");
                while (rs.next()) {
                    System.out.println("after rs.next");
                    rs.getString(1);
                         /* itp.reservation.model.CustomerDetails Cd = new   itp.reservation.model.CustomerDetails();
                     
                     Cd .setCname(rs.getString(1));
                     Cd.setCemail(rs.getString(2));
                     Cd.setCcontact(rs.getString(3));
                     System.out.println("print in ");
                     System.out.println(Cd);
                     
                       arrList.add(Cd);*/
                     
                    
                     

              /*  }
               
                                     System.out.println("result"+arrList);
      
            jTable2.setModel(model);
                   
                   
          
     
        } catch (SQLException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }*/
                l.setVisible(true);
            
        }
    }//GEN-LAST:event_ViewDetailsbtnActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNHome;
    private javax.swing.JButton BTNlogout;
    private javax.swing.JButton ReservationRhistory;
    private javax.swing.JButton ViewDetailsbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    
}
